# Generated by Django 5.1 on 2024-08-13 03:00

import timescale.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketSymbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('market', models.CharField(max_length=50)),
                ('asset_type', models.CharField(max_length=50)),
                ('ipo_date', models.DateField(blank=True, null=True)),
                ('delisting_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'market_symbol',
            },
        ),
        migrations.CreateModel(
            name='MarketStockHistoricalBars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', timescale.db.models.fields.TimescaleDateTimeField(interval='1 day')),
                ('symbol', models.CharField(default='NaN', max_length=10)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.FloatField()),
                ('trade_count', models.FloatField()),
                ('volume_weighted_average_price', models.FloatField()),
            ],
            options={
                'db_table': 'market_stock_hist_bars_ts',
                'indexes': [models.Index(fields=['symbol', 'time'], name='market_stoc_symbol_cf39b0_idx')],
                'constraints': [models.UniqueConstraint(fields=('symbol', 'time'), name='symbol_timestamp_pk')],
            },
        ),
    ]
