# Generated by Django 5.1.4 on 2024-12-23 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='investment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='margin_loan',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='add_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='pick_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='purpose',
            field=models.CharField(blank=True, choices=[('0', 'Normal'), ('1', 'SEPA'), ('2', 'EARNING')], default='0', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='snapshotoverview',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_phase',
            field=models.CharField(choices=[('0', 'None'), ('1', 'Before Breakout'), ('2', 'Breaking Out'), ('3', 'After Breakout'), ('4', 'Earning')], default='0', max_length=20),
        ),
    ]
