# Generated by Django 5.1 on 2024-09-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='utilitieslookup',
            name='utilities_lookup_category_type_pk',
        ),
        migrations.AddConstraint(
            model_name='utilitieslookup',
            constraint=models.UniqueConstraint(fields=('category', 'type', 'key'), name='utilities_lookup_category_type_key_pk'),
        ),
    ]
