# Generated by Django 5.1 on 2024-09-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_remove_utilitieslookup_utilities_lookup_category_type_pk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilitieslookup',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
