# Generated by Django 5.1 on 2024-09-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_utilitieslookup_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilitiesFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('sub_category', models.CharField(max_length=255)),
                ('filter', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'utilities_filter',
            },
        ),
    ]
