# Generated by Django 5.1 on 2024-09-18 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_utilitiesfilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilitiesfilter',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
