# Generated by Django 5.1 on 2024-09-18 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_utilitiesfilter_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilitiesfilter',
            old_name='category',
            new_name='key',
        ),
        migrations.RenameField(
            model_name='utilitiesfilter',
            old_name='filter',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='utilitiesfilter',
            old_name='sub_category',
            new_name='value',
        ),
    ]
