# Generated by Django 5.1 on 2024-09-20 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_rename_category_utilitiesfilter_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketsymbol',
            old_name='is_delisted_on_day',
            new_name='is_delisted',
        ),
        migrations.RemoveField(
            model_name='marketsymbol',
            name='is_delisted_on_min',
        ),
    ]
