# Generated by Django 5.1 on 2024-09-20 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_rename_is_delisted_on_day_marketsymbol_is_delisted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchStockVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('avg_volume_50', models.BigIntegerField(blank=True, null=True)),
                ('avg_volume_5', models.BigIntegerField(blank=True, null=True)),
                ('symbol', models.ForeignKey(db_column='symbol', on_delete=django.db.models.deletion.DO_NOTHING, related_name='research_stock_volume', to='common.marketsymbol')),
            ],
            options={
                'db_table': 'research_stock_volume',
            },
        ),
    ]
