# Generated by Django 5.1 on 2024-08-19 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notification',
            unique_together=set(),
        ),
    ]
